baseURL                = "https://www.tood.win/"
locale                 = "zh"
title                  = "我的博客"
theme = "hugo-theme-stack"
# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "zh"
# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage = true
enableGitInfo = true
enableRobotsTXT = true

[sitemap]
    changeFreq = "weekly"
    filename   = "sitemap.xml"
    priority   = 0.5



[pagination]
    pagerSize = 3

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = "hugo-theme-stack"
